# Generated by Django 5.1.7 on 2025-03-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='book_author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AddField(
            model_name='post',
            name='book_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=3),
        ),
        migrations.AddField(
            model_name='post',
            name='reading_status',
            field=models.CharField(choices=[('currently_reading', 'Currently Reading'), ('finished', 'Finished'), ('want_to_read', 'Want to Read'), ('dnf', 'Did Not Finish')], default='finished', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='recommended',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Share your thoughts about the book'),
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ManyToManyField(blank=True, to='blog.genre'),
        ),
    ]
